# Generated by Django 2.2 on 2020-12-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhysicalTherapy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
