# Generated by Django 2.2 on 2020-12-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhysicalTherapy', '0002_delete_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['id']},
        ),
    ]
