# Generated by Django 2.2 on 2020-10-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20201014_0555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'default_permissions': (), 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'default_permissions': (), 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'default_permissions': (), 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'default_permissions': (), 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'default_permissions': (), 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'default_permissions': (), 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
