# Generated by Django 2.2 on 2020-11-23 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Services', '0002_service_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patients', '0008_auto_20201120_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('visits_added', models.IntegerField(default=1, verbose_name='عدد الزيارات المضافة')),
                ('price', models.FloatField(default=0, verbose_name='سعر الخدمة')),
                ('discount', models.FloatField(default=0, verbose_name='خصم')),
                ('after_discount', models.FloatField(default=0, verbose_name='بعد الخصم')),
                ('visits_used', models.IntegerField(default=1, verbose_name='عدد الزيارات المستخدمة')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.Patient', verbose_name='المريض')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Services.Service', verbose_name='الخدمة')),
            ],
        ),
    ]
