# Generated by Django 2.2 on 2020-12-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20201014_0724'),
        ('Invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Instance'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.FloatField(default=0, verbose_name='المدفوع'),
        ),
    ]
