# Generated by Django 2.2 on 2020-12-02 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20201014_0724'),
        ('Invoices', '0002_auto_20201201_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='outcome',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='منصرف'),
        ),
        migrations.CreateModel(
            name='OutcomeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='اسم التصنيف')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Instance')),
            ],
        ),
    ]
