# Generated by Django 2.2 on 2020-12-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_auto_20201202_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomecategory',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
    ]
