# Generated by Django 2.2 on 2020-12-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0005_auto_20201202_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.IntegerField(choices=[(1, 'سند قبض نقدية'), (2, 'سند صرف نقدية')], default=1, verbose_name='النوع'),
        ),
    ]
