# Generated by Django 2.2 on 2020-12-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0006_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_invoice',
            field=models.BooleanField(default=False, verbose_name='فاتورة'),
        ),
    ]
