# Generated by Django 2.2 on 2020-11-01 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='اسم التحليل')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='اسم الخاصية')),
                ('normal_min', models.FloatField(blank=True, null=True, verbose_name='طبيعي من')),
                ('normal_max', models.FloatField(blank=True, null=True, verbose_name='طبيعي حتي')),
                ('unit', models.CharField(blank=True, max_length=128, null=True, verbose_name='وحدة القياس')),
                ('lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LabTest.LabTest')),
            ],
        ),
    ]
