# Generated by Django 2.2 on 2020-11-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
    ]
