# Generated by Django 2.2 on 2020-11-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='اسم الخدمة')),
                ('price', models.FloatField(verbose_name='سعر الخدمة')),
                ('number_of_visits', models.IntegerField(verbose_name='عدد الزيارات')),
            ],
        ),
    ]
