# Generated by Django 2.2 on 2020-11-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
    ]
