# Generated by Django 2.2 on 2020-12-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20201014_0724'),
        ('Services', '0002_service_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Instance'),
        ),
    ]
