# Generated by Django 2.2 on 2020-11-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_auto_20201129_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='نهاية الجلسة'),
        ),
    ]
