# Generated by Django 2.2 on 2020-11-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0008_auto_20201120_0643'),
        ('Calendar', '0003_appointment_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='count',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='queue',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queue',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.Patient', verbose_name='المريض'),
        ),
    ]
