# Generated by Django 2.2 on 2020-11-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radiology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='اسم الاشعة')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
    ]
