# Generated by Django 2.2 on 2020-10-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0003_auto_20201014_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='نوع السرطان')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الشكوي')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='المرض')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('gender', models.IntegerField(choices=[(1, 'ذكر'), (2, 'أنثي')], verbose_name='الجنس')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم الهاتف')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.Area', verbose_name='المنطقة')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.City', verbose_name='المدينة')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.Instance')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.Job', verbose_name='الوظيفة')),
            ],
        ),
        migrations.CreateModel(
            name='PatientViralProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='درجة الحرارة')),
                ('Pulse', models.FloatField(blank=True, null=True, verbose_name='معدل النبض')),
                ('blood_pressure_high', models.IntegerField(blank=True, null=True, verbose_name='الضغط الانقباضي')),
                ('blood_pressure_low', models.IntegerField(blank=True, null=True, verbose_name='الضغط الانبساطي')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='معدل التنفس')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient', verbose_name='المريض')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_blood_pressure', models.BooleanField(verbose_name='مريض ضغط')),
                ('dvt', models.BooleanField(verbose_name='تجلط الأوردة')),
                ('lung_disease', models.BooleanField(verbose_name='أمراض الرئة')),
                ('stroke', models.BooleanField(verbose_name='أصيب بسكتة دماغية؟')),
                ('high_cholesterol', models.BooleanField(verbose_name='زيادة نسبة الكوليسترول')),
                ('pulmonary_embolism', models.BooleanField(verbose_name='انسداد رئوي')),
                ('asthma', models.BooleanField(verbose_name='مريض ربو')),
                ('vein_trouble', models.BooleanField(verbose_name='مشاكل في الوريد')),
                ('tuberculosis', models.BooleanField(verbose_name='مرض السل')),
                ('heart_trouble', models.BooleanField(verbose_name='مشاكل في القلب')),
                ('pneumonia', models.BooleanField(verbose_name='التهاب رئوي')),
                ('kidney_disease', models.BooleanField(verbose_name='مريض كبد')),
                ('nervous_disorder', models.BooleanField(verbose_name='اضطراب عصبي')),
                ('seasonal_allergies', models.BooleanField(verbose_name='حساسية موسمية')),
                ('hiv', models.BooleanField(verbose_name='مريض إيدز')),
                ('thyroid_problems', models.BooleanField(verbose_name='مشاكل في الغدة الدرقية')),
                ('sinus', models.BooleanField(verbose_name='حساسية في الجيوب الانفية')),
                ('arthritis', models.BooleanField(verbose_name='التهاب في المفاصل')),
                ('hepatitis', models.BooleanField(verbose_name='التهاب في الكبد')),
                ('drug_abuse_alcoholism', models.BooleanField(verbose_name='متعاطي مخدرات/كحوليات')),
                ('tonsilitis', models.BooleanField(verbose_name='التهاب في اللوز')),
                ('gastrointestinal', models.BooleanField(verbose_name='مشاكل في الجهاز الهضمي')),
                ('osteoporosis', models.BooleanField(verbose_name='هشاشة عظام')),
                ('joint_replacement', models.BooleanField(verbose_name='استبدال مفاصل')),
                ('bleeding_tendencies', models.BooleanField(verbose_name='سيولة في الدم')),
                ('cancer', models.BooleanField(verbose_name='سرطان')),
                ('cancer_type', models.BooleanField(verbose_name='أنواع السرطان')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient', verbose_name='المريض')),
            ],
        ),
        migrations.CreateModel(
            name='HeightAndWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('height', models.FloatField(verbose_name='الطول بالـ cm')),
                ('weight', models.FloatField(verbose_name='الوزن بالـ kg')),
                ('bmi', models.FloatField(verbose_name='معدل الكتلة')),
                ('weight_status', models.IntegerField(choices=[(1, 'تحت الوزن الطبيعي'), (2, 'طبيعي'), (3, 'وزن زائد'), (4, 'سمنة I'), (5, 'سمنة II'), (6, 'سمنة III')], verbose_name='حالة الوزن')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient', verbose_name='المريض')),
            ],
        ),
    ]
