# Generated by Django 2.2 on 2020-10-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_history',
            field=models.ManyToManyField(blank=True, to='Patients.Disease', verbose_name='التاريخ المرضي'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='arthritis',
            field=models.BooleanField(default=False, verbose_name='التهاب في المفاصل'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='asthma',
            field=models.BooleanField(default=False, verbose_name='مريض ربو'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='bleeding_tendencies',
            field=models.BooleanField(default=False, verbose_name='سيولة في الدم'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='cancer',
            field=models.BooleanField(default=False, verbose_name='سرطان'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='cancer_type',
            field=models.BooleanField(default=False, verbose_name='أنواع السرطان'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='drug_abuse_alcoholism',
            field=models.BooleanField(default=False, verbose_name='متعاطي مخدرات/كحوليات'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='dvt',
            field=models.BooleanField(default=False, verbose_name='تجلط الأوردة'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='gastrointestinal',
            field=models.BooleanField(default=False, verbose_name='مشاكل في الجهاز الهضمي'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='heart_trouble',
            field=models.BooleanField(default=False, verbose_name='مشاكل في القلب'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='hepatitis',
            field=models.BooleanField(default=False, verbose_name='التهاب في الكبد'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='high_blood_pressure',
            field=models.BooleanField(default=False, verbose_name='مريض ضغط'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='high_cholesterol',
            field=models.BooleanField(default=False, verbose_name='زيادة نسبة الكوليسترول'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='hiv',
            field=models.BooleanField(default=False, verbose_name='مريض إيدز'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='joint_replacement',
            field=models.BooleanField(default=False, verbose_name='استبدال مفاصل'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='kidney_disease',
            field=models.BooleanField(default=False, verbose_name='مريض كبد'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='lung_disease',
            field=models.BooleanField(default=False, verbose_name='أمراض الرئة'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='nervous_disorder',
            field=models.BooleanField(default=False, verbose_name='اضطراب عصبي'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='osteoporosis',
            field=models.BooleanField(default=False, verbose_name='هشاشة عظام'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='pneumonia',
            field=models.BooleanField(default=False, verbose_name='التهاب رئوي'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='pulmonary_embolism',
            field=models.BooleanField(default=False, verbose_name='انسداد رئوي'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='seasonal_allergies',
            field=models.BooleanField(default=False, verbose_name='حساسية موسمية'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='sinus',
            field=models.BooleanField(default=False, verbose_name='حساسية في الجيوب الانفية'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='stroke',
            field=models.BooleanField(default=False, verbose_name='أصيب بسكتة دماغية؟'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='thyroid_problems',
            field=models.BooleanField(default=False, verbose_name='مشاكل في الغدة الدرقية'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='tonsilitis',
            field=models.BooleanField(default=False, verbose_name='التهاب في اللوز'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='tuberculosis',
            field=models.BooleanField(default=False, verbose_name='مرض السل'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='vein_trouble',
            field=models.BooleanField(default=False, verbose_name='مشاكل في الوريد'),
        ),
    ]
