# Generated by Django 2.2 on 2020-11-01 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabTest', '0001_initial'),
        ('Patients', '0002_auto_20201017_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LabTest.LabTest', verbose_name='التحليل المطلوب')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='القيمة')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabTest.LabTestAttribute', verbose_name='الخاصية')),
                ('lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.LabTestRequest', verbose_name='التحليل')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientInvestigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('medical_plan', models.TextField(verbose_name='الخطة العلاجية')),
                ('complain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.Complain', verbose_name='الشكوي')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.Disease', verbose_name='التشخيص')),
            ],
        ),
        migrations.RenameField(
            model_name='heightandweight',
            old_name='date_added',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='date_added',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='patientviralprocess',
            old_name='date_added',
            new_name='added_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='الزيارات'),
        ),
        migrations.DeleteModel(
            name='PatientMedicalHistory',
        ),
        migrations.AddField(
            model_name='patientinvestigation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient', verbose_name='المريض'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient', verbose_name='المريض'),
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient', verbose_name='المريض'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient', verbose_name='المريض'),
        ),
    ]
