# Generated by Django 2.2 on 2020-11-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0003_auto_20201101_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heightandweight',
            name='bmi',
            field=models.FloatField(blank=True, null=True, verbose_name='معدل الكتلة'),
        ),
        migrations.AlterField(
            model_name='heightandweight',
            name='weight_status',
            field=models.IntegerField(blank=True, choices=[(1, 'تحت الوزن الطبيعي'), (2, 'طبيعي'), (3, 'وزن زائد'), (4, 'سمنة I'), (5, 'سمنة II'), (6, 'سمنة III')], null=True, verbose_name='حالة الوزن'),
        ),
    ]
