# Generated by Django 2.2 on 2020-11-16 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabTest', '0002_labtest_deleted'),
        ('Patients', '0004_auto_20201101_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heightandweight',
            options={'ordering': ['added_at']},
        ),
        migrations.AlterModelOptions(
            name='labtestrequest',
            options={'ordering': ['added_at']},
        ),
        migrations.AlterModelOptions(
            name='medicalprescription',
            options={'ordering': ['added_at']},
        ),
        migrations.AlterModelOptions(
            name='patienthistory',
            options={'ordering': ['added_at']},
        ),
        migrations.AlterModelOptions(
            name='patientinvestigation',
            options={'ordering': ['added_at']},
        ),
        migrations.AlterModelOptions(
            name='patientviralprocess',
            options={'ordering': ['added_at']},
        ),
        migrations.AlterField(
            model_name='labtestresult',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='القيمة'),
        ),
        migrations.CreateModel(
            name='RadiologyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient', verbose_name='المريض')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='الصورة')),
                ('lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LabTest.LabTest', verbose_name='التحليل')),
            ],
        ),
    ]
