# Generated by Django 2.2 on 2020-11-16 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Radiology', '0001_initial'),
        ('Patients', '0005_auto_20201116_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyrequest',
            name='radiology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Radiology.Radiology', verbose_name='الآشعة'),
        ),
    ]
