# Generated by Django 2.2 on 2020-11-16 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0006_radiologyrequest_radiology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestimages',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.LabTestRequest', verbose_name='التحليل'),
        ),
        migrations.CreateModel(
            name='RadiologyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='الملخص')),
                ('radiology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patients.RadiologyRequest', verbose_name='الآشعة')),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='الصورة')),
                ('radiology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.RadiologyRequest', verbose_name='الآشعة')),
            ],
        ),
    ]
