# Generated by Django 2.2 on 2020-11-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0007_auto_20201116_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestimages',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='radiologyimages',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='التاريخ'),
        ),
    ]
