# Generated by Django 2.2 on 2020-12-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0008_auto_20201120_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='التشخيص')),
            ],
        ),
        migrations.AlterField(
            model_name='patientinvestigation',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.Diagnosis', verbose_name='التشخيص'),
        ),
        migrations.AlterField(
            model_name='patientinvestigation',
            name='medical_plan',
            field=models.TextField(blank=True, null=True, verbose_name='الخطة العلاجية'),
        ),
    ]
