# Generated by Django 2.2 on 2020-12-13 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhysicalTherapy', '0002_delete_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0003_auto_20201014_0724'),
        ('Patients', '0009_auto_20201213_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinvestigation',
            name='devices',
            field=models.ManyToManyField(blank=True, to='PhysicalTherapy.Device', verbose_name='الأجهزة'),
        ),
        migrations.AddField(
            model_name='patientinvestigation',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='PhysicalTherapy.Exercise', verbose_name='التمرينات'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('devices', models.ManyToManyField(to='PhysicalTherapy.Device', verbose_name='الأجهزة المستخدمة')),
                ('exercises', models.ManyToManyField(to='PhysicalTherapy.Exercise', verbose_name='التمارين المستخدمة')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Instance')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient')),
            ],
        ),
    ]
