# Generated by Django 2.2 on 2020-12-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0004_auto_20201129_0533'),
        ('Patients', '0012_prescription_prescriptionitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrescriptionItems',
            new_name='PrescriptionItem',
        ),
    ]
