# Generated by Django 2.2 on 2021-01-15 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patients', '0013_auto_20201223_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload/patient_images/', verbose_name='الصورة')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient')),
            ],
        ),
    ]
