# Generated by Django 2.2 on 2021-01-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0014_patientimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdiet',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف النظام'),
        ),
    ]
