# Generated by Django 2.2 on 2021-02-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0015_patientdiet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medicines.Dose', verbose_name='الجرعة'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medicines.Medicine', verbose_name='الدواء'),
        ),
    ]
