# Generated by Django 2.2 on 2021-02-01 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0006_timing'),
        ('Patients', '0016_auto_20210201_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medicines.Timing', verbose_name='التوقيت'),
        ),
    ]
