# Generated by Django 2.2 on 2021-02-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0017_prescriptionitem_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='electricity_img',
            field=models.ImageField(blank=True, null=True, upload_to='electricity/', verbose_name='صورة الكهرباء'),
        ),
    ]
