# Generated by Django 2.2 on 2021-03-08 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patients', '0018_patient_electricity_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='patientdiet',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='patientimage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان الصفحة')),
                ('body', models.TextField(verbose_name='النص')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient', verbose_name='المريض')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
