# Generated by Django 2.2 on 2020-11-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=128, verbose_name='الاسم التجاري')),
                ('scientific_name', models.CharField(max_length=128, verbose_name='الاسم العلمي')),
                ('company', models.CharField(max_length=128, verbose_name='الشركة المنتجة')),
                ('price', models.FloatField(default=0.0, verbose_name='السعر')),
                ('ingredient', models.IntegerField(verbose_name='التركيز')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
    ]
