# Generated by Django 2.2 on 2020-11-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='scientific_name',
        ),
        migrations.AddField(
            model_name='medicine',
            name='family',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='العائلة'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='الاسم العلمي'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='الشركة المنتجة'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='ingredient',
            field=models.IntegerField(blank=True, null=True, verbose_name='التركيز'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='السعر'),
        ),
    ]
