# Generated by Django 2.2 on 2020-11-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0002_auto_20201123_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='family',
            new_name='pharmacology',
        ),
    ]
