# Generated by Django 2.2 on 2020-11-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0003_auto_20201123_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='pharmacology',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='فارماكولوجي'),
        ),
    ]
