# Generated by Django 2.2 on 2020-12-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('cost_price', models.FloatField(verbose_name='سعر التكلفة')),
                ('sell_price', models.FloatField(verbose_name='سعر البيع')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
    ]
